# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Crud Application test

on: push

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install dependencies
      run: |
        cd Web
        npm install
    - name: Run Test code
      run: |
        cd Web
        npm run test
